version: 1.0.{build}
configuration: Release
platform: Any CPU
branches:
  only:
  - master
  - Dev
cache:
- .\packages -> .\**\packages.config
before_build:
- cmd: nuget restore .\Maple.sln -Verbosity quiet
build:
    parallel: true
    project: .\Maple.sln
    verbosity: minimal
artifacts:
- path: './Maple/bin/$(configuration)'
  name: '.-Binaries'
