version: 0.0.{build}
configuration: Release
platform: Any CPU
image:
  - Visual Studio 2017

skip_commits:
  files:
    - appveyor.yml
    - README.md

environment:
  APPVEYOR_REPO_TAG: true

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  only:
    - master

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
  - .\packages -> .\**\packages.config

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: powershell -ExecutionPolicy ByPass -File ".\Cake\build.ps1" -Script ".\Cake\build.cake"

#---------------------------------#
#  Build Artifacts                #
#---------------------------------#
artifacts:
  - path: './src/Maple/bin/$(configuration)'
    name: 'Binaries'
  - path: './Cake/Archive/'
    name: 'Installer'
  - path: './Cake/Releases/'
    name: 'AutoUpdates'

#---------------------------------#
#  Unit Tests                     #
#---------------------------------#
test: off

#---------------------------------#
#  Deploy to GitHub Releases      #
#---------------------------------#
deploy:
  #release: Maple-v$(appveyor_build_version)
  description: 'Auto generated build' # is required to be set
  #tag: 'Test tag'
  #realease: 'Test release name'
  provider: GitHub
  auth_token:
    secure: Yo5d5V9sj0vLGZl6XQ1N4aNajAja6FTmPkRyr1Ft3Vg5fhPTFCPuh4d0LqcQvNZy # your encrypted token from GitHub
  artifact: Binaries,Installer,AutoUpdates
  draft: true
  prerelease: true
  force_update: true
  on:
    branch: master                # release from master branch only
    APPVEYOR_REPO_TAG: true       # deploy on tag push only