version: 1.0.{build}
configuration: Release
platform: Any CPU
branches:
  only:
  - master
  - Dev
cache:
- InsireBot\packages -> InsireBot\**\packages.config
before_build:
- cmd: nuget restore InsireBot\Maple.sln
build:
    parallel: true
    project: InsireBot\Maple.sln
    verbosity: minimal
artifacts:
- path: 'InsireBot/InsireBot/bin/$(configuration)'
  name: 'InsireBot-Binaries'
build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - MSBuild.SonarQube.Runner.exe begin /k:"Maple" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=D4KL4CL9XXNHCDJRHGHF4"
  - msbuild "InsireBot\Maple.sln"
  - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=D4KL4CL9XXNHCDJRHGHF4"