version: 1.0.{build}
configuration: Release
platform: Any CPU
cache:
- InsireBot\packages -> InsireBot\**\packages.config
before_build:
- cmd: nuget restore InsireBot\Maple.sln
build:
  project: InsireBot\Maple.sln
  verbosity: minimal
artifacts:
- path: 'InsireBot/InsireBot/bin/$(configuration)'
  name: 'InsireBot-Binaries'
