version: 1.0.{build}
configuration: Release
platform: Any CPU
branches:
  only:
  - master
  - Dev
environment:
  SonarToken:
    secure: 3mBbvKwFSmV0pgVwRLH70+9YekT4I109T09+PlHRThu9rbVUybSPBZrrheWECXq+
  SonarProject:
    secure: XBMwudirgqiNxzCuNA+rgYPCdCjNypfboJruML+pNKg=
cache:
- InsireBot\packages -> InsireBot\**\packages.config
before_build:
- cmd: nuget restore InsireBot\Maple.sln
build:
    parallel: true
    project: InsireBot\Maple.sln
    verbosity: minimal
artifacts:
- path: 'InsireBot/InsireBot/bin/$(configuration)'
  name: 'InsireBot-Binaries'
build_script:
  - choco install "msbuild-sonarqube-runner" -y
  - MSBuild.SonarQube.Runner.exe begin /k:%SonarProject% /n:"Maple" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=%SonarToken%"
  - msbuild "InsireBot\Maple.sln"
  - MSBuild.SonarQube.Runner.exe end /d:"sonar.login=%SonarToken%"