version: 1.0.{build}
configuration: Release
platform: Any CPU
branches:
  only:
  - master
  - Dev
cache:
- InsireBot\packages -> InsireBot\**\packages.config
before_build:
- cmd: nuget restore InsireBot\Maple.sln -Verbosity quiet
build:
    parallel: true
    project: InsireBot\Maple.sln
    verbosity: minimal
artifacts:
- path: 'InsireBot/InsireBot/bin/$(configuration)'
  name: 'InsireBot-Binaries'
