version: 1.0.{build}
configuration: Release
platform: Any CPU
image: Visual Studio 2017

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  only:
    - master
    - Dev

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
  - .\packages -> .\**\packages.config
  - .\Cake\tools -> setup.cake

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: powershell -ExecutionPolicy ByPass -File ".\Cake\build.ps1" -target "Default" -Script ".\Cake\build.cake"
  
#---------------------------------#
#  Build Artifacts                #
#---------------------------------#
artifacts:
  - path: './src/Maple/bin/$(configuration)'
    name: '.-Binaries'
