version: 1.0.{build}
configuration: Release
platform: Any CPU

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  only:
    - master
    - Dev

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
  - .\packages -> .\**\packages.config
  - tools -> setup.cake

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1
  
#---------------------------------#
#  Build Artifacts                #
#---------------------------------#
artifacts:
  - path: './Maple/bin/$(configuration)'
    name: '.-Binaries'
